# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf3f7d24cc3daa4cf2c8a6d529d89225162e9f6445f2126914a9adc42a8a873147d97953c0f77044917d7ea43a4676a13fe2dfb33adb3493a337b76b5f1745fb

test:
  secret_key_base: bf7e5021a49167fbbbf30f0765e4803b1bc0d13bca51960bc08e2a10f0ea21da54958a48240ed8561392b39f4510597684d8d58cfeef2c5c058cd734a91a4e78

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
